#********************************** IMPORT ***************************************

import pytest
from unittest.mock import patch, mock_open
from utils.enums import AccessLevel
from model.user_model import UserModel

#*********************************************************************************

# Scope: test_user_model.py is generated by ChatGPT-4o
# Tool: ChatGPT-4o
# GPT Prompt:  "How can I use pytest to test user_model.py? Can you generate for me?"

@pytest.fixture
def mock_file_ops():
    """
    Mock file operations for user database.
    """
    initial_data = "{}"
    m = mock_open(read_data=initial_data)
    with patch('builtins.open', m), \
         patch('os.path.exists', return_value=True), \
         patch('json.dump'), \
         patch('json.load', return_value={}):
        yield m

def test_user_model_init(mock_file_ops):
    
    # Initialize UserModel
    um = UserModel()
    assert "1" in um._users
    assert um._users["1"]["access_level"] == AccessLevel.Master.value
    assert um._users["1"]["password"] == "1"

def test_authenticate_success(mock_file_ops):
    
    # Test successful authentication
    with patch('json.load', return_value={"1": {"password": "1", "access_level": AccessLevel.Master.value}}):
        um = UserModel()
        is_auth, msg, level = um.authenticate("1", "1")
        assert is_auth is True
        assert "match" in msg
        assert level == AccessLevel.Master.value

def test_authenticate_wrong_password(mock_file_ops):
    
    # Test wrong password 
    with patch('json.load', return_value={"admin": {"password": "correct", "access_level": AccessLevel.Admin.value}}):
        um = UserModel()
        is_auth, msg, level = um.authenticate("admin", "wrong")
        assert is_auth is False
        assert "wrong" in msg
        assert level is None

def test_add_user_success(mock_file_ops):
    
    # Test succeeded in adding a new user
    with patch('json.load', return_value={"1": {"password": "1", "access_level": AccessLevel.Master.value}}):
        um = UserModel()
        result = um.add_user("user2", "password2", AccessLevel.User)
        assert result is True
        assert "user2" in um._users
        assert um._users["user2"]["access_level"] == AccessLevel.User.value

def test_add_user_duplicate(mock_file_ops):
    
    #  Test to add an existing user
    with patch('json.load', return_value={"1": {"password": "1", "access_level": AccessLevel.Master.value}}):
        um = UserModel()
        result = um.add_user("1", "new_pass", AccessLevel.User)
        assert result is False

def test_check_access_success(mock_file_ops):
    
    # Test check_access successfully
    with patch('json.load', return_value={
        "admin": {"password": "adminpass", "access_level": AccessLevel.Master.value}
    }):
        um = UserModel()
        is_access, msg = um.check_access("admin", "adminpass", AccessLevel.User)
        assert is_access is True
        assert "New account can be added" in msg

def test_check_access_failure_insufficient_level(mock_file_ops):
    
    # Test lower access level
    with patch('json.load', return_value={
        "normaladmin": {"password": "adminpass", "access_level": AccessLevel.Admin.value}
    }):
        um = UserModel()
        is_access, msg = um.check_access("normaladmin", "adminpass", AccessLevel.Master)
        assert is_access is False
        assert "must be higher" in msg


