#********************************** IMPORT ***************************************

import pytest
from unittest.mock import patch
from model.electrical_device_model import Television, Lamp, BedsideLamp, Refrigerator, ElectricKettle, AirConditioner
from utils.enums import TwoStatus
from utils import config
from utils.enums import ACStatus

#*********************************************************************************

# Scope: test_electrical_device_model.py is generated by ChatGPT-4o
# Tool: ChatGPT-4o
# GPT Prompt:  "How can I use pytest to test electrical_device_model.py? Can you generate for me?"

def test_television_on_off():
    tv = Television(device_id=1)
    assert tv.status == TwoStatus.OFF.value
    assert tv.power_rating == 0
    assert tv.heating_rate == 0


    tv.switch_up()
    assert tv.status == TwoStatus.ON.value
    assert tv.power_rating == config.DEVICE_CONFIG["Television"]["power_rating"]
    assert tv.heating_rate == config.DEVICE_CONFIG["Television"]["heating_rate"]

    tv.switch_down()
    assert tv.status == TwoStatus.OFF.value
    assert tv.power_rating == 0
    assert tv.heating_rate == 0

def test_lamp_on_off():
    lamp = Lamp(device_id=2)
    assert lamp.status == TwoStatus.OFF.value
    lamp.switch_up()
    assert lamp.status == TwoStatus.ON.value
    assert lamp.power_rating == config.DEVICE_CONFIG["Lamp"]["power_rating"]
    assert lamp.heating_rate == config.DEVICE_CONFIG["Lamp"]["heating_rate"]
    lamp.switch_down()
    assert lamp.status == TwoStatus.OFF.value
    assert lamp.power_rating == 0
    assert lamp.heating_rate == 0

def test_bedside_lamp_on_off():
    bedside_lamp = BedsideLamp(device_id=3)
    assert bedside_lamp.status == TwoStatus.OFF.value
    bedside_lamp.switch_up()
    assert bedside_lamp.status == TwoStatus.ON.value
    assert bedside_lamp.power_rating == config.DEVICE_CONFIG["Bedside Lamp"]["power_rating"]
    assert bedside_lamp.heating_rate == config.DEVICE_CONFIG["Bedside Lamp"]["heating_rate"]
    bedside_lamp.switch_down()
    assert bedside_lamp.status == TwoStatus.OFF.value
    assert bedside_lamp.power_rating == 0
    assert bedside_lamp.heating_rate == 0

def test_refrigerator_on_off():
    fridge = Refrigerator(device_id=4)
    assert fridge.status == TwoStatus.OFF.value
    fridge.switch_up()
    assert fridge.status == TwoStatus.ON.value
    assert fridge.power_rating == config.DEVICE_CONFIG["Refrigerator"]["power_rating"]
    assert fridge.heating_rate == config.DEVICE_CONFIG["Refrigerator"]["heating_rate"]
    fridge.switch_down()
    assert fridge.status == TwoStatus.OFF.value
    assert fridge.power_rating == 0
    assert fridge.heating_rate == 0

def test_electric_kettle_on_off():
    kettle = ElectricKettle(device_id=5)
    assert kettle.status == TwoStatus.OFF.value
    kettle.switch_up()
    assert kettle.status == TwoStatus.ON.value
    assert kettle.power_rating == config.DEVICE_CONFIG["Electric Kettle"]["power_rating"]
    assert kettle.heating_rate == config.DEVICE_CONFIG["Electric Kettle"]["heating_rate"]
    kettle.switch_down()
    assert kettle.status == TwoStatus.OFF.value
    assert kettle.power_rating == 0
    assert kettle.heating_rate == 0
    
def test_air_conditioner_initial_state():
    ac = AirConditioner(device_id=101)
    assert ac.status == 0
    assert ac.power_rating == config.AIR_CONDITIONER_CONFIG[ACStatus.OFF]["power"]
    assert ac.heating_rate == config.AIR_CONDITIONER_CONFIG[ACStatus.OFF]["heating_rate"]

def test_air_conditioner_switch_up_levels():
    ac = AirConditioner(device_id=102)

    start_level = ac.status
    ac.switch_up()  # From 0 to 1 
    assert ac.status == 1
    assert ac.power_rating == config.AIR_CONDITIONER_CONFIG[ACStatus.HEATING_LEVEL_1]["power"]
    assert ac.heating_rate == config.AIR_CONDITIONER_CONFIG[ACStatus.HEATING_LEVEL_1]["heating_rate"]

    ac.switch_up()  # From 1 to 2 
    assert ac.status == 2
    assert ac.power_rating == config.AIR_CONDITIONER_CONFIG[ACStatus.HEATING_LEVEL_2]["power"]
    assert ac.heating_rate == config.AIR_CONDITIONER_CONFIG[ACStatus.HEATING_LEVEL_2]["heating_rate"]

def test_air_conditioner_switch_down_levels():
    ac = AirConditioner(device_id=103)
    
    ac.switch_up()  # From 0 to 1
    ac.switch_up()  # From 1 to 2
    
    ac.switch_down()  # From 2 to 1
    assert ac.status == 1
    assert ac.power_rating == config.AIR_CONDITIONER_CONFIG[ACStatus.HEATING_LEVEL_1]["power"]
    assert ac.heating_rate == config.AIR_CONDITIONER_CONFIG[ACStatus.HEATING_LEVEL_1]["heating_rate"]
