#********************************** IMPORT ***************************************

import pytest
from unittest.mock import MagicMock
from controller.controller import AuthController, MainController
from utils.enums import AccessLevel

#*********************************************************************************

# Scope: test_controller.py is generated by ChatGPT-4o
# Tool: ChatGPT-4o
# GPT Prompt:  "How can I use pytest to test controller.py? Can you generate for me?"

# -------------------- AuthController Tests --------------------

def test_auth_controller_login_success():
    auth = AuthController()
    auth._user_model.authenticate = MagicMock(return_value=(True, "Login success", AccessLevel.User))
    success, message, level = auth.login("user123", "password")
    assert success is True
    assert message == "Login success"
    assert level == AccessLevel.User

def test_auth_controller_login_failure():
    auth = AuthController()
    auth._user_model.authenticate = MagicMock(return_value=(False, "Invalid credentials", None))
    with pytest.raises(ValueError) as excinfo:
        auth.login("user123", "wrongpass")
    assert "Invalid credentials" in str(excinfo.value)

def test_auth_controller_check_access_success():
    auth = AuthController()
    auth._user_model.check_access = MagicMock(return_value=(True, "OK"))
    success, msg = auth.check_access("admin", "adminpass", AccessLevel.Admin)
    assert success is True
    assert msg == "Register successfully"

def test_auth_controller_check_access_failure():
    auth = AuthController()
    auth._user_model.check_access = MagicMock(return_value=(False, "No access"))
    with pytest.raises(ValueError) as excinfo:
        auth.check_access("nonexist", "pass", AccessLevel.Admin)
    assert "Username does not exist" in str(excinfo.value)

def test_auth_controller_register_success_admin():
    auth = AuthController()
    auth._user_model.add_user = MagicMock(return_value=True)
    success, message = auth.register("admin123", "adminpass", AccessLevel.Admin)
    assert success is True
    assert message == "Admin registered successfully"

def test_auth_controller_register_success_user():
    auth = AuthController()
    auth._user_model.add_user = MagicMock(return_value=True)
    success, message = auth.register("user456", "userpass", AccessLevel.User)
    assert success is True
    assert message == "User registered successfully"

def test_auth_controller_register_failure():
    auth = AuthController()
    auth._user_model.add_user = MagicMock(return_value=False)
    with pytest.raises(ValueError) as excinfo:
        auth.register("user789", "userpass", AccessLevel.User)
    assert "User already exists" in str(excinfo.value)

# -------------------- MainController Tests --------------------

def test_main_controller_initialize_tabs_in_view():
    main_ctrl = MainController()
    main_ctrl.main_model.get_tab_full_names = MagicMock(return_value=["Welcome", "LivingRoom1"])
    view_mock = MagicMock()
    main_ctrl.initialize_tabs_in_view(view_mock)
    
    # Check add_tab_button
    view_mock.add_tab_button.assert_any_call("Welcome")
    view_mock.add_tab_button.assert_any_call("LivingRoom1")
    main_ctrl.show_tab_content = MagicMock()  

def test_main_controller_add_device_success():
    main_ctrl = MainController()
    main_ctrl.main_model.get_tab_full_names = MagicMock(return_value=["LivingRoom1"])
    main_ctrl.main_model.add_device = MagicMock(return_value=(True, "Device added"))
    main_ctrl.main_model.save_tabs = MagicMock()
    main_ctrl.show_tab_content = MagicMock()

    success, _ = main_ctrl.add_device("LivingRoom1", "Lamp")
    assert success is True
    main_ctrl.main_model.add_device.assert_called_once_with("LivingRoom1", "Lamp")
    main_ctrl.show_tab_content.assert_called_once_with("LivingRoom1")

def test_main_controller_add_device_room_not_found():
    main_ctrl = MainController()
    main_ctrl.main_model.get_tab_full_names = MagicMock(return_value=["Kitchen1"])
    with pytest.raises(ValueError) as excinfo:
        main_ctrl.add_device("LivingRoom1", "Lamp")
    assert "Room LivingRoom1 not found." in str(excinfo.value)

def test_main_controller_remove_device_success():
    main_ctrl = MainController()
    main_ctrl.main_model.remove_current_device = MagicMock()
    main_ctrl.main_model.save_tabs = MagicMock()
    main_ctrl.show_tab_content = MagicMock()

    success, _ = main_ctrl.remove_current_device("Kitchen1", "Lamp1")
    assert success is True
    main_ctrl.main_model.remove_current_device.assert_called_once_with("Kitchen1", "Lamp1")
    main_ctrl.show_tab_content.assert_called_once_with("Kitchen1")

def test_main_controller_remove_device_failure():
    main_ctrl = MainController()
    main_ctrl.main_model.remove_current_device = MagicMock(side_effect=ValueError("Device not found"))
    with pytest.raises(ValueError) as excinfo:
        main_ctrl.remove_current_device("Kitchen1", "NonExistDevice")
    assert "Device not found" in str(excinfo.value)

def test_main_controller_change_device_state_invalid_direction():
    main_ctrl = MainController()

    with pytest.raises(ValueError) as excinfo:
        main_ctrl.change_device_state("LivingRoom1", "TV1", "LEFT")
    assert "Invalid direction: LEFT" in str(excinfo.value)

def test_main_controller_change_device_state_success():
    main_ctrl = MainController()
    main_ctrl.main_model.change_device_state = MagicMock()
    main_ctrl.main_model.save_tabs = MagicMock()
    main_ctrl.show_tab_content = MagicMock()

    # Test valid state changes
    main_ctrl.change_device_state("LivingRoom1", "TV1", "UP")
    main_ctrl.main_model.change_device_state.assert_called_once_with("LivingRoom1", "TV1", "UP")
    main_ctrl.show_tab_content.assert_called_once_with("LivingRoom1")
