#********************************** IMPORT ***************************************

from unittest.mock import MagicMock, patch
import pytest
from model.main_model import MainModel, WelcomeModel, RoomTabModel

#*********************************************************************************

# Scope: test_main_model.py is generated by ChatGPT-4o
# Tool: ChatGPT-4o
# GPT Prompt:  "How can I use pytest to test main_model.py? Can you generate for me?"

@patch('model.main_model.MainModel.save_tabs', return_value=None)
def test_main_model_get_tab_full_names(mock_save_tabs):
    main_model = MainModel()
    main_model.tabs = [
        WelcomeModel("Welcome", 0, "Welcome Message"),
        MagicMock(tab_full_name="LivingRoom1"),
        MagicMock(tab_full_name="Kitchen1")
    ]
    names = main_model.get_tab_full_names()
    assert names == ["Welcome", "LivingRoom1", "Kitchen1"]

@patch('model.main_model.MainModel.save_tabs', return_value=None)
def test_main_model_add_device_success(mock_save_tabs):
    main_model = MainModel()
    fake_tab = MagicMock(spec=RoomTabModel)
    fake_tab.tab_full_name = "LivingRoom1"
    fake_tab.add_device_to_room = MagicMock(return_value=MagicMock(device_type="Television"))
    main_model.tabs = [
        WelcomeModel("Welcome", 0, "Welcome Message"),
        fake_tab
    ]

    success, msg = main_model.add_device("LivingRoom1", "Television")
    assert success is True
    assert "Device Television added successfully" in msg
    fake_tab.add_device_to_room.assert_called_once_with("Television")

@patch('model.main_model.MainModel.save_tabs', return_value=None)
def test_main_model_add_device_tab_not_found(mock_save_tabs):
    main_model = MainModel()
    main_model.tabs = [WelcomeModel("Welcome", 0, "Welcome Message")]

    success, msg = main_model.add_device("NonExistTab", "Television")
    assert success is False
    assert "Tab 'NonExistTab' not found." in msg

@patch('model.main_model.MainModel.save_tabs', return_value=None)
def test_main_model_remove_device_success(mock_save_tabs):
    main_model = MainModel()
    fake_tab = MagicMock(spec=RoomTabModel)
    fake_tab.tab_full_name = "LivingRoom1"
    main_model.tabs = [
        WelcomeModel("Welcome", 0, "Welcome Message"),
        fake_tab
    ]

    success, msg = main_model.remove_current_device("LivingRoom1", "Television1")
    assert success is True
    assert "Device Television1 removed successfully" in msg
    fake_tab.remove_device_from_room.assert_called_once_with("Television1")

@patch('model.main_model.MainModel.save_tabs', return_value=None)
def test_main_model_remove_device_tab_not_found(mock_save_tabs):
    main_model = MainModel()
    main_model.tabs = [WelcomeModel("Welcome", 0, "Welcome Message")]

    success, msg = main_model.remove_current_device("NonExistTab", "Television1")
    assert success is False
    assert "Tab 'NonExistTab' not found." in msg

@patch('model.main_model.MainModel.save_tabs', return_value=None)
def test_main_model_change_device_state(mock_save_tabs):
    main_model = MainModel()
    fake_tab = MagicMock(spec=RoomTabModel)
    fake_tab.tab_full_name = "LivingRoom1"
    main_model.tabs = [
        WelcomeModel("Welcome", 0, "Welcome Message"),
        fake_tab
    ]

    main_model.change_device_state("LivingRoom1", "Television1", "UP")
    fake_tab.change_device_state.assert_called_once_with("Television1", "UP")

@patch('model.main_model.MainModel.save_tabs', return_value=None)
def test_main_model_change_device_state_tab_not_found(mock_save_tabs):
    main_model = MainModel()
    main_model.tabs = [WelcomeModel("Welcome", 0, "Welcome Message")]

    with pytest.raises(ValueError) as exc:
        main_model.change_device_state("NonExistTab", "Television1", "UP")
    assert "Tab full name: NonExistTab is invalid" in str(exc.value)
