#********************************** IMPORT ***************************************

import pytest
from unittest.mock import patch, MagicMock
from model.room_model import Room

#*********************************************************************************

# Scope: test_room_model.py is generated by ChatGPT-4o
# Tool: ChatGPT-4o
# GPT Prompt:  "How can I use pytest to test room_model.py? Can you generate for me?"

@pytest.fixture
def mock_config():
    with patch('model.room_model.config') as mock_config:
        mock_config.ROOM_START_TEMPERATURE = 20.0
        mock_config.TEMPERATURE_CHANGE_HEATING_RATE_CONSTANT = 0.1
        mock_config.TEMPERATURE_CHANGE_REFRESH_RATE = 0.1
        mock_config.CENTER_AIR_CONDITIONER_TEMPERATURE_CHANGE_RATE = 0.5
        mock_config.TEMPERATURE_LOWEER_BOUND = 18.0
        mock_config.TEMPERATURE_UPPER_BOUND = 25.0
        mock_config.TEMPERATURE_AVERAGE = 21.5
        yield mock_config

@pytest.fixture
def mock_enums():

    with patch('model.room_model.RoomType') as MockRoomType:
        MockRoomType.KITCHEN.value = "Kitchen"
        MockRoomType.LIVING_ROOM.value = "LivingRoom"
        MockRoomType.BEDROOM.value = "Bedroom"
        yield MockRoomType

@pytest.fixture
def mock_devices_config():
    
    # Mock VALID_DEVICES和MAX_QUANTITY
    with patch('model.room_model.VALID_DEVICES') as mock_valid_devices:
        mock_valid_devices.__getitem__.return_value = ["Lamp", "Television"]  
        with patch('model.room_model.MAX_QUANTITY') as mock_max_quantity:
            mock_max_quantity.__getitem__.return_value = {
                "Lamp": 2,
                "Television": 1
            }
            yield mock_valid_devices, mock_max_quantity

@pytest.fixture
def mock_elec_app():
    
    with patch('model.room_model.elec_app') as mock_elec:
        
        # Return a simple MagicMock class for each device type
        LampMock = MagicMock()
        LampMock.device_type = "Lamp"
        LampMock.heating_rate = 1.0
        TelevisionMock = MagicMock()
        TelevisionMock.device_type = "Television"
        TelevisionMock.heating_rate = 2.0

        def create_device(device_type, id_):
            d = MagicMock()
            d.device_type = device_type
            d.device_id = id_
            d.device_full_name = f"{device_type}_{id_}"
            d.heating_rate = 1.0 if device_type == "Lamp" else 2.0
            return d

        mock_elec.Lamp.side_effect = lambda dt, i: create_device(dt, i)
        mock_elec.Television.side_effect = lambda dt, i: create_device(dt, i)
        yield mock_elec

@pytest.fixture
def room_instance(mock_config, mock_enums, mock_devices_config, mock_elec_app):
    
    # Create a base Room instance
    r = Room(room_type="LivingRoom", room_id=101)
    return r


def test_remove_device_not_found(room_instance):
    
    # Delete a nonexistent device
    with pytest.raises(ValueError) as exc_info:
        room_instance.remove_current_device("Lamp_999")
    assert "No device" in str(exc_info.value)

